[lib]
crate-type = ["cdylib"]
name = "myfilter"

[package]
name = "my-wasm-filter"
version = "0.1.0"
edition = "2021"

[dependencies]
proxy-wasm = "0.2.3"
log = "0.4"
tract-onnx = "0.16.9"
tokenizers = { version = "0.13.4", default-features = false, features = ["unstable_wasm"] }

